language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - MODULE_NAME=opening_hours
    - COMPOSER_MEMORY_LIMIT=-1
  matrix:
    - DRUPAL=8.9
    - DRUPAL=9.0
    - DRUPAL=9.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Update & configure composer.
  - composer self-update --2
  - composer --version
  - composer config github-oauth.github.com ${GITHUB_TOKEN}
  - composer config --global --auth http-basic.digipolis.repo.repman.io token ${REPMAN_TOKEN}

  # Remember directories for later use.
  - export DRUPAL_DIR="$TRAVIS_BUILD_DIR/../drupal"
  - export MODULE_DIR="$DRUPAL_DIR/web/modules/$MODULE_NAME"

  # Get the CodeClimate test reporter.
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  # Install Module.
  - composer install --no-interaction --no-progress

  # Install Drupal.
  - composer create-project "drupal/recommended-project:$DRUPAL.x-dev" "$DRUPAL_DIR" --prefer-dist --no-interaction --no-progress

  # Install Drupal Check.
  - composer require mglaman/drupal-check:1.1.3 --working-dir="$DRUPAL_DIR" --no-interaction --no-progress

before_script:
  # Link to module from within Drupal.
  - ln -s . "$MODULE_DIR"

script:
  # Run GrumPHP checks.
  - vendor/bin/grumphp run

  # Test for deprecations.
  - cd "$DRUPAL_DIR"
  - phpenv config-rm xdebug.ini
  - ./vendor/bin/drupal-check -ad "$MODULE_DIR"

after_script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
