<?php

/**
 * @file
 * Module hooks.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function opening_hours_theme($existing, $type, $theme, $path) {
  return [
    'opening_hours_widget' => [
      'template' => 'opening-hours-widget',
      'path' => $path . '/templates',
      'variables' => [
        'preview_widget' => NULL,
        'widgets' => NULL,
        'service_id' => NULL,
        'display_title' => NULL,
        'channel_id' => NULL,
        'single_widget' => NULL,
        'date' => NULL,
        'from' => NULL,
        'until' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess().
 */
function template_preprocess_opening_hours_widget(&$variables) {
  $variables['widget_id'] = Html::getUniqueId('opening_hours');
}
